- name: EC2インスタンス削除
  shell: aws ec2 terminate-instances --instance-ids "{{ ec2_id }}"
  register: ec2_delete_info

- name: ec2削除確認
  debug:
    msg: "{{ ec2_delete_info.stdout }}"

- name: ec2が終了済みになるまで待機
  shell: aws ec2 describe-instances --instance-ids "{{ ec2_id }}" --query "Reservations[].Instances[].State.Name | [0]" | tr -d "\""
  register: state
  until: state.stdout == "terminated"
  retries: 18
  delay: 10